---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test
  - script/travis-deploy.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

env: # IAM: travis-s3
  secure: RdzCMUHB2dtmCc0IHEdIAvqItRhT45HLcr0C5s+lHIoImsNXatjjuHgOeCKlzn9Ewkx7Jkxt5q5ZBeOrQLEh8JTorGqrlpf40BQ46qd5tIScqwvQ4f2c6y06HGOzC2mbl1PK6w/7k76JfWcH0SNDG6exuCYViXkWhHb1oGxlJfA=
