---
language: node_js

cache:
  directories:
    - node_modules

before_install: # These steps lifted from https://github.com/sass/node-sass/issues/497#issuecomment-62552565
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - sudo g++ --version;
  - sudo apt-get update -qq;

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
